# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(default=datetime.datetime(2016, 9, 24, 6, 40, 20, 349000))),
            ],
        ),
    ]
